### ISSUE TITLE
keylogger broken

### ISSUE THREAD

**Issue by Invoke-Mimikatz** [CarlJamison/miseryjs#1]
<img width="293" alt="image" src="https://user-images.githubusercontent.com/57604669/196471473-6ae82bb8-97d2-4f9f-be98-34ecd90993a0.png">

<img width="377" alt="image" src="https://user-images.githubusercontent.com/57604669/196471557-f9bb89b9-aeff-447e-980b-5e39b5e15af6.png">

Add support for special characters, backspace, tabs, enter/return.

Add support for CaSe SeNsItIvItY!!

Also possible to show title of the current window when keys were pressed?

**Comment by Invoke-Mimikatz** [comment]
Keylogger is getting better! However, client side HTML escaping is not the way to do input sanitation. We need to implement this on the server side.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/57604669/199283429-c8f3f2c5-cd07-47d7-8104-c9d432a1d932.png">

I have removed the HTML escaping code from the keylogger in commit 47040766b00b1557f73fb175562a22c975c3756f since it is useless. 

<img width="1101" alt="image" src="https://user-images.githubusercontent.com/57604669/199285120-6a50c3a4-dc49-4d63-97c3-941292a40375.png">

Keylogger is still vulnerable to XSS. Solution to this is to escape the keylogger output **server side** using something like [this](https://www.npmjs.com/package/escape-html) (or maybe other NodeJS HTML escape implementation).

**Comment by CarlJamison** [comment]
should be fixed now, pls verify

**Comment by Invoke-Mimikatz** [comment]
<img width="813" alt="image" src="https://user-images.githubusercontent.com/57604669/199644041-e197bd6a-5ec2-496a-8ed9-05e1acbf0962.png">

Seems like the `tainted-keylogger.dll` can't inject javascript code into the operator webpage any more!

lgtm!
