### ISSUE TITLE
cannot perform actions on files whose names contain spaces (i.e. "new file.txt")

### ISSUE THREAD

**Issue by jbroberg42** [CarlJamison/miseryjs#4]
A solution I propose is using an escape character plus a space (i.e. "\ + <space>") to designate a space that is part of the filename: "new file.txt" becomes "new\ file.txt"

unable to attach screenshot... github won't let me :(

**Comment by Invoke-Mimikatz** [comment]
Looks like this is a "feature" related to the commands.json argument aliases syntax (specifically`{*}`). This is not unique to the `Filesystem` module. In the below picture you can see running a command via its alias (`bypass`) doesn't matter if it has quotes. In the 2nd and 3rd commands, quotes do matter (running it directly with `run`).

<img width="513" alt="image" src="https://user-images.githubusercontent.com/57604669/199530776-27228114-041b-45fa-8a1e-8b4b6778b220.png">

<img width="392" alt="image" src="https://user-images.githubusercontent.com/57604669/199532966-9e8c66fd-7a9e-45ed-a595-0e8df85839db.png">

Seems like this is probably a bug in the alias code [here](https://github.com/CarlJamison/miseryjs/blob/e1b6e19fadb24d4a48d9bd18897321efbe74b209/public/index.html#L97).

@CarlJamison 
![carl](https://user-images.githubusercontent.com/57604669/199533270-6b05679a-859e-47e2-837c-19f8b0c1a9b0.gif)

**Comment by CarlJamison** [comment]
should be fixed, now just need quotes around spaced args.  pls verify

**Comment by Invoke-Mimikatz** [comment]
Seems like that fixed it. Only have to 2x escape backslashes when used inside quotes 😹 

<img width="620" alt="image" src="https://user-images.githubusercontent.com/57604669/199644946-e34affab-e765-4af6-87b5-49aecb15bffc.png">

Fixed in b1354c5d01a786f40253440777dd6a6087b3bc15
